commands = [
  { savefile_manager = "ctrl+o" },
  { item_spawner = "ctrl+u" },
  { character_stats = true },
  { cycle_speed = [0.5, 1.0, 2.0, 5.0], hotkey = "8" },
  { cycle_color = [0, 1, 2, 3] },
  { souls = 10000, hotkey = "9" },
  { open_menu = "travel" },
  { open_menu = "attune" },
  { group = "Positions", commands = [
    { nudge = 1.0, nudge_up = "[", nudge_down = "]" },
    { position = "h", save = "rshift+h" },
    { position = "j", save = "rshift+j" },
    { position = "k", save = "rshift+k" },
  ]},
  { group = "Render flags", commands = [
    { flag = "rend_chr", hotkey = "f4" },
    { flag = "rend_obj", hotkey = "f5" },
    { flag = "rend_map", hotkey = "f6" },
    { flag = "rend_mesh_hi", hotkey = "f7" },
    { flag = "rend_mesh_lo", hotkey = "f8" },
    # { flag = "all_draw_hit" }, # conflicts with debug_draw
    { flag = "ik_foot_ray" },
    { flag = "debug_sphere_1" },
    { flag = "debug_sphere_2" },
    { flag = "evt_draw" },
    { label = "" },
    { label = "Below needs debug draw enabled:" },
    { flag = "debug_draw" },
    { flag = "hurtbox" },
    { flag = "bloodstain_draw" },
  ]},
  { flag = "all_no_damage", hotkey = "1" },
  { flag = "inf_stamina", hotkey = "2" },
  { flag = "inf_focus", hotkey = "3" },
  { flag = "inf_consumables", hotkey = "4" },
  { flag = "deathcam", hotkey = "5" },
  { flag = "no_death", hotkey = "6" },
  { flag = "one_shot", hotkey = "7" },
  { flag = "ember", hotkey = "o" },
  { target = "ctrl+n" },
  { flag = "ai_disable", hotkey = "f1" },
  { flag = "gravity", hotkey = "f2" },
  { flag = "collision", hotkey = "f3" },
  { flag = "evt_disable", hotkey = "f9" },
  { quitout = "p" }
]

radial-menu = [
  { index = 23, label = "Quitout" },
  { index = 0, label = "Load savefile" },
  { index = 10, label = "No Damage" },
  { index = 18, label = "Target Info" },
  { index = 19, label = "AI Disable" },
]

[settings]
log_level = "DEBUG"
display = "0"
hide = "rshift+0"
show_console = false
indicators = [
  { indicator = "game_version", enabled = true },
  { indicator = "igt", enabled = true },
  { indicator = "position", enabled = false },
  { indicator = "position_change", enabled = false },
  { indicator = "animation", enabled = false },
  { indicator = "fps", enabled = false },
  { indicator = "framecount", enabled = false },
  { indicator = "imgui_debug", enabled = false }
]
