commands = [
  { group = "Actions", commands = [
    { savefile_manager = "o" },
    { item_spawner = "u" },
    { character_stats = "end" },
    { cycle_speed = [1, 3], hotkey = "8" },
    { souls = 10000, hotkey = "9" },
    { open_menu = "travel" },
    { open_menu = "attune" },
  ]},
  { group = "Positions", commands = [
    { nudge = 1.0, nudge_up = "[", nudge_down = "]" },
    { position = "H", modifier = "rshift" },
    { position = "J", modifier = "rshift" },
    { position = "K", modifier = "rshift" },
  ]},
  { target = "N" },
  { flag = "all_no_damage", hotkey = "1" },
  { flag = "inf_stamina", hotkey = "2" },
  { flag = "inf_focus", hotkey = "3" },
  { flag = "inf_consumables", hotkey = "4" },
  { flag = "deathcam", hotkey = "5" },
  { flag = "no_death", hotkey = "6" },
  { flag = "one_shot", hotkey = "7" },
  { flag = "evt_draw", hotkey = "F1" },
  { flag = "evt_disable", hotkey = "F2" },
  { flag = "ai_disable", hotkey = "F3" },
  { flag = "rend_chr", hotkey = "F4" },
  { flag = "rend_obj", hotkey = "F5" },
  { flag = "rend_map", hotkey = "F6" },
  { flag = "rend_mesh_hi", hotkey = "F7" },
  { flag = "rend_mesh_lo", hotkey = "F8" },
  { flag = "all_draw_hit", hotkey = "F9" },
  { flag = "ik_foot_ray", hotkey = "F9" },
  { flag = "debug_sphere_1", hotkey = "F9" },
  { flag = "debug_sphere_2", hotkey = "F9" },
  { flag = "gravity", hotkey = "F10" },
  { quitout = "P" }
]

[settings]
log_level = "DEBUG"
display = "0"
show_console = false
