[build]
target = ["x86_64-pc-windows-msvc"]
rustflags = ["-C", "link-args=-Wl,--subsystem,windows"]

[alias]
brl = "build --release --lib"
xtask = "run --package xtask --"
r = "run --package xtask -- run"
